product_product:
    resource: "@ProductBundle/Controller"
    prefix: /
    type:     annotation

#product:
#    resource: "@ProductBundle/Resources/config/routing.yml"
#    prefix:   /

user:
    resource: "@UserBundle/Controller"
    type: annotation
app:
    resource: '@AppBundle/Controller/'
    type: annotation
admin:
    resource: '@ProductBundle/Controller/AdminController.php'
    type: annotation