security:
    encoders:
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_users:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout
                target: event
            anonymous: ~
            switch_user: ~
            remember_me:
                key: "Order 1138"
            #http_basic:
            #    realm: "Secured Demo Area"

#    access_control:
#    - { path: ^/admin, role: ROLE_ADMIN }
#    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
#    - { path: ^/, roles: ROLE_USER }
#    - { path: ^/product, role: ROLE_USER }
#    - { path: ^/products, role: ROLE_USER }


