<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function findOneByUsernameOrEmail($username)
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult()
            ->execute();

    }

    public function loadUserByUsername($username)
    {
        $user = $this->findOneByUsernameOrEmail($username);

        if (!$user) {
            throw new UsernameNotFoundException('No user found for username '.$username);
        }

        return $user;
    }

    //todo verify this works as expected
    public function loadMostActiveUsers()
    {
        return $this->createQueryBuilder('u')
            ->select(['u.username', 'COUNT(*)'])
            ->from('User','u')
            ->innerJoin('ProductBundle\Entity\Reviews','r')
            ->groupBy('r.user_id')
            ->orderBy('COUNT(*)')
            ->orderBy('COUNT(*)','DESC')
            ->getQuery()
            ->execute();
    }
}
