<?php

namespace ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
/*    public function loadTopRatedProducts($count = 5)
    {
        $this->createQueryBuilder()
            ->innerJoin('Reviews')
            ->groupBy('id')
            ->orderBy('rating')
    }*/
}
