<?php

namespace ProductBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function loadTopRatedProducts($limit = 5)
    {
        $query = $this->getEntityManager()->createQuery('SELECT p.id, p.name, AVG(r.rating) product_rate FROM ProductBundle\Entity\Product p 
                                                            JOIN ProductBundle\Entity\Reviews r WHERE p.id = r.products 
                                                            GROUP BY r.products ORDER BY product_rate DESC')->setMaxResults($limit);

        return $query->getResult();
    }

    public function loadAverageProductRating($productId)
    {
        $query = $this->getEntityManager()->createQuery('SELECT p.name, AVG(r.rating) product_rate FROM ProductBundle\Entity\Product p 
                                                            JOIN ProductBundle\Entity\Reviews r WHERE p.id = ?1 
                                                            GROUP BY r.products');
        $query->setParameter(1,$productId);

        return $query->getResult();
    }

    public function loadFirstProducts($limit = 10)
    {
        return $this->findBy([],null, $limit);
    }

    public function selectStar()
    {
        $query = $this->getEntityManager()->createQuery('SELECT r.id FROM ProductBundle\Entity\Product p JOIN ProductBundle\Entity\Reviews r WHERE p.id = r.products 
                                                            ');

        return $query->getResult();
    }

}
