<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewsRepository extends EntityRepository
{
    public function loadProductReviewsByUser()
    {
        //todo verify this works as expected
        $this->createQueryBuilder('p')
            ->select(['p.name','r.rating','u.username', 'r.is_approved'])
            ->from('Reviews','r')
            ->innerJoin('Product', 'p')
            ->innerJoin('UserBundle\Entity\User','u');
    }
}
