<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewsRepository extends EntityRepository
{
    public function loadProductReviewsByUser()
    {

        $query = $this->getEntityManager()->createQuery('SELECT r.id, p.id AS productId, p.name AS productName, r.rating, r.description, r.isApproved , r.rating, u.username FROM ProductBundle\Entity\Reviews r 
                                                                JOIN ProductBundle\Entity\Product p WHERE r.products = p.id
                                                                JOIN UserBundle\Entity\User u WHERE u.id = r.user
                                                                ORDER BY r.id DESC
                                                        ');

        return $query->getResult();
    }

    public function loadAverageProductRating($productId)
    {

        $query = $this->getEntityManager()->createQuery('SELECT p.name, AVG(r.rating) FROM ProductBundle\Entity\Reviews r 
                                                                JOIN ProductBundle\Entity\Product p 
                                                                WHERE r.products = p.id AND p.id = :productId
                                                        ');
        $query->setParameter('productId', $productId);

        return $query->getResult();
    }

    public function selectStar()
    {
        $query = $this->getEntityManager()->createQuery('SELECT r.id , r.rating FROM ProductBundle\Entity\Reviews r JOIN ProductBundle\Entity\Product p WHERE r.products = p.id 
                                                            ');

        return $query->getResult();
    }
}
